name: env_django
channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.12
  - django
  - flake8
  - black
prefix: /home/ali/anaconda3/envs/env_django
